

###
GET http://localhost:5220/
Accept: application/xml

###
GET http://localhost:5220/product/12


###
PUT http://localhost:5220/product/12
Content-Type: application/json

{
"id": 12,
"name": "Product 12",
"description": "Product 12 description",
"price": 12.34,
"rating": 99
}